# Generated by Django 3.0.6 on 2020-05-31 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=250, null=True)),
                ('channels', models.IntegerField(blank=True, null=True)),
                ('sampwidth', models.IntegerField(blank=True, null=True)),
                ('framerate', models.IntegerField(blank=True, null=True)),
                ('nframes', models.IntegerField(blank=True, null=True)),
                ('audiogram', models.BinaryField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'In Queue'), (5, 'In Progress'), (10, 'Done')], default=1)),
            ],
        ),
    ]
